name: vgmart
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.5
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  google_fonts: ^3.0.1

  # firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.9
  firebase_remote_config: ^3.0.9

  image_picker: ^0.8.6
  flex_color_scheme: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/grocery/

