// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8yGljpno1TokCacUrvxovXkJjyu1If2A',
    appId: '1:1068263221493:web:8e58a5124a55d96c8c7dbc',
    messagingSenderId: '1068263221493',
    projectId: 'vg-mart',
    authDomain: 'vg-mart.firebaseapp.com',
    storageBucket: 'vg-mart.appspot.com',
    measurementId: 'G-JHHFCY06J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXNAYclO09ZsRwXqeeanzXICm0HzMX_c',
    appId: '1:1068263221493:android:d00328338ddb47458c7dbc',
    messagingSenderId: '1068263221493',
    projectId: 'vg-mart',
    storageBucket: 'vg-mart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7oaSwCgL8wsnscaWs2tRVBNBPUxhPc8',
    appId: '1:1068263221493:ios:f0c25934c8205a318c7dbc',
    messagingSenderId: '1068263221493',
    projectId: 'vg-mart',
    storageBucket: 'vg-mart.appspot.com',
    androidClientId: '1068263221493-4ht1mnoghv9a3ranooo8unlmn46nb4sg.apps.googleusercontent.com',
    iosClientId: '1068263221493-n0d7vurqnvsedumtangj5oradhj38n6e.apps.googleusercontent.com',
    iosBundleId: 'com.vgmartapp.vgmart',
  );
}
